name: "Setup"
runs:
    using: "composite"
    steps:
        - uses: cachix/install-nix-action@v30
          with:
              nix_path: nixpkgs=channel:nixos-unstable
        - name: Cache .venv
          id: cache-venv
          uses: actions/cache@v3
          with:
              path: |
                  .venv
                  node_modules
                  !.venv/postgresql
              key: ${{ runner.os }}-nix-cache-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/*.nix') }}
        - name: Get pip cache dir
          id: pip-cache-dir
          run: |
              echo "::set-output name=dir::$(pip3 cache dir)"
          shell: bash
        - name: pip cache
          uses: actions/cache@v3
          with:
              path: |
                  ~/.cache/ms-playwright
                  /Users/runner/Library/Caches/ms-playwright
                  ${{ steps.pip-cache-dir.outputs.dir }}
              key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        - name: Get npm cache directory
          id: npm-cache-dir
          run: |
              echo "::set-output name=dir::$(npm config get cache)"
          shell: bash
        - uses: actions/cache@v3
          id: npm-cache
          with:
              path: ${{ steps.npm-cache-dir.outputs.dir }}
              key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        - name: "MacOS python venv issue"
          # On macOS, the first time you setup venv a really weird issue happens
          # and site-packages is not in sys.path. I cannot figure out why, no files
          # or env variables change in between nix-shell runs.
          if: runner.os == 'macOS'
          shell: bash
          run: nix-shell --command ""
        - name: Build
          run: nix-shell --command "npm install && python scripts/generate_types.py && npm exec -w reactivated tsc && playwright install && npm install"
          shell: bash
        - name: Fix greenlet
          if: runner.os == 'Linux'
          run: nix-shell --command "pip install greenlet==3.0.3 --no-binary greenlet --force-reinstall"
          shell: bash
