name: "Setup"
runs:
    using: "composite"
    steps:
        - uses: cachix/install-nix-action@v15
          with:
              nix_path: nixpkgs=channel:nixos-unstable
        - name: Cache nix env take N+1
          uses: actions/cache@v2
          with:
              path: |
                  # See https://github.com/actions/cache/pull/726
                  /nix/**
              key: ${{ runner.os }}-nix-store
        - name: Nix requirements
          run: nix-shell
          shell: bash
        - name: Build
          run: nix-shell --command "npm install && python scripts/generate_types.py && npm exec -w reactivated tsc && playwright install && npm install"
          shell: bash
