# Generated by Django 5.0.2 on 2026-03-21 21:00

import reactivated.constraints
import reactivated.fields
from django.db import migrations

import server.example.models


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="status",
            field=reactivated.fields.EnumField(
                default=server.example.models.Question.Status["DRAFT"],
                enum=server.example.models.Question.Status,
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=reactivated.constraints.EnumConstraint(
                field_name="status",
                members=["DRAFT", "PUBLISHED", "CLOSED"],
                name="example_question_status_enum",
            ),
        ),
    ]
