# Generated by Django 4.0.1 on 2022-01-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_text",
            field=models.CharField(max_length=200, verbose_name="question"),
        ),
    ]
