/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Schema {
  TrinketListProps: TrinketListProps;
  TrinketDetailProps: TrinketDetailProps;
  NewThing: NewThing;
  FormViewProps: FormViewProps;
}
export interface TrinketListProps {
  trinket_list: Trinket[];
  template_name: string;
  csrf_token: string;
}
export interface Trinket {
  name: string;
  url: string;
}
export interface TrinketDetailProps {
  trinket: Trinket1;
  back_url: string;
  template_name: string;
  csrf_token: string;
}
export interface Trinket1 {
  name: string;
  url: string;
}
export interface NewThing {
  a: string;
  b: {
    [k: string]: any;
  };
  c: NestedNewThing;
  template_name: string;
  csrf_token: string;
}
export interface NestedNewThing {
  b: {
    [k: string]: any;
  };
  f: number;
}
export interface FormViewProps {
  widget_list: Trinket2[];
  form: FormType;
  template_name: string;
  csrf_token: string;
}
export interface Trinket2 {
  name: string;
  url: string;
}
export interface FormType {
  errors: {
    [k: string]: string[] | null;
  };
  fields: FieldType[];
}
export interface FieldType {
  name: string;
  label: string;
}
