# Generated by Django 3.0.10 on 2020-09-19 02:10

from django.db import migrations, models
import reactivated.constraints
import reactivated.fields
import sample.server.apps.samples.models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Two',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hemisphere', reactivated.fields.EnumField(default=sample.server.apps.samples.models.Thing['ONE'], enum=sample.server.apps.samples.models.Thing)),
            ],
        ),
        migrations.AddConstraint(
            model_name='two',
            constraint=reactivated.constraints.EnumConstraint(field_name='hemisphere', members=['ONE', 'TWO'], name='samples_two_hemisphere_enum'),
        ),
    ]
