# Generated by Django 5.0.2 on 2024-08-15 03:02

import reactivated.constraints
import reactivated.fields
import sample.server.apps.samples.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0002_opera_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="opera",
            name="tags",
            field=reactivated.fields.EnumArrayField(
                base_field=reactivated.fields.EnumField(
                    enum=sample.server.apps.samples.models.Opera.Tag
                ),
                default=[],
                enum=sample.server.apps.samples.models.Opera.Tag,
                size=None,
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="opera",
            constraint=reactivated.constraints.EnumConstraint(
                field_name="tags",
                is_array=True,
                members=["MELODIC", "ROMANTIC", "LONG"],
                name="samples_opera_tags_enum",
            ),
        ),
    ]
