# Generated by Django 3.1.1 on 2020-09-19 23:50

from django.db import migrations
import reactivated.constraints
import reactivated.fields
import sample.server.apps.samples.models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_auto_20200919_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='two',
            name='hemisphere2',
            field=reactivated.fields._EnumField(default=sample.server.apps.samples.models.Thing['ONE'], enum=sample.server.apps.samples.models.Thing),
        ),
        migrations.AddConstraint(
            model_name='two',
            constraint=reactivated.constraints.EnumConstraint(field_name='hemisphere2', members=['ONE', 'TWO'], name='samples_two_hemisphere2_enum'),
        ),
    ]
