# Generated by Django 3.1.1 on 2020-09-20 00:08

from django.db import migrations

import reactivated.constraints


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0003_auto_20200920_0008"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="two", name="samples_two_hemisphere_enum",
        ),
        migrations.RemoveConstraint(
            model_name="two", name="samples_two_hemisphere2_enum",
        ),
        migrations.RemoveField(model_name="two", name="hemisphere2",),
        migrations.AddConstraint(
            model_name="two",
            constraint=reactivated.constraints.EnumConstraint(
                field_name="hemisphere",
                members=["ONE", "TWO", "THREE"],
                name="samples_two_hemisphere_enum",
            ),
        ),
    ]
