# Generated by Django 3.1.1 on 2020-09-20 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0004_auto_20200920_0008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Two',
        ),
    ]
