# Generated by Django 3.0.10 on 2020-09-19 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0004_auto_20200919_0210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Two',
        ),
    ]
