# Generated by Django 3.1.1 on 2020-09-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0004_auto_20200919_1709'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Two',
        ),
    ]
