# Generated by Django 3.1.1 on 2020-09-19 17:18

from django.db import migrations
import reactivated.constraints
import reactivated.fields
import sample.server.apps.samples.models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0005_delete_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='opera',
            name='style',
            field=reactivated.fields.EnumField(default=sample.server.apps.samples.models.Opera.Style['GRAND'], enum=sample.server.apps.samples.models.Opera.Style),
        ),
        migrations.AddConstraint(
            model_name='opera',
            constraint=reactivated.constraints.EnumConstraint(field_name='style', members=['VERISMO', 'BUFFA', 'GRAND'], name='samples_opera_style_enum'),
        ),
    ]
